// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeError-0]
	_ = x[TypeQueue-1]
	_ = x[TypeApply-2]
	_ = x[TypePrune-3]
	_ = x[TypeInventory-4]
}

const _Type_name = "ErrorQueueApplyPruneInventory"

var _Type_index = [...]uint8{0, 5, 10, 15, 20, 29}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
