// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package poller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusInProgress-0]
	_ = x[StatusFailed-1]
	_ = x[StatusTerminating-2]
	_ = x[StatusCurrent-3]
}

const _Status_name = "InProgressFailedTerminatingCurrent"

var _Status_index = [...]uint8{0, 10, 16, 27, 34}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
